/* SupplierSpliterator.vala
 *
 * Copyright (C) 2019-2020  Космическое П. (kosmospredanie@yandex.ru)
 *
 * This file is part of Gpseq.
 *
 * Gpseq is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * Gpseq is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Gpseq.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Gpseq {
	/**
	 * An infinite unordered spliterator, which each element is generated by a
	 * supplier.
	 */
	public class SupplierSpliterator<G> : Object, Spliterator<G> {
		private Supplier<G> _supplier;

		/**
		 * Creates a new supplier spliterator.
		 * @param supplier a supplier
		 */
		public SupplierSpliterator (Supplier<G> supplier) {
			_supplier = supplier;
		}

		public Spliterator<G>? try_split () {
			return new SupplierSpliterator<G>(_supplier);
		}

		public bool try_advance (Func<G> consumer) throws Error {
			consumer(_supplier.supply());
			return true;
		}

		public int64 estimated_size {
			get {
				return -1;
			}
		}

		public bool is_size_known {
			get {
				return true;
			}
		}
	}
}
